#!/bin/sh

TMP_DIFF_FILE=$(mktemp)
git diff --cached > "$TMP_DIFF_FILE"

if [ ! -s "$TMP_DIFF_FILE" ]; then
  rm "$TMP_DIFF_FILE"
  exit 0
fi

DIFF_SIZE=$(wc -c < "$TMP_DIFF_FILE")
echo "Diff size: $DIFF_SIZE bytes"
# MAX_SIZE=100000
# if [ "$DIFF_SIZE" -gt "$MAX_SIZE" ]; then
#   echo "Diff quá lớn: $DIFF_SIZE bytes, vượt quá giới hạn $MAX_SIZE bytes"
#   rm "$TMP_DIFF_FILE"
#   exit 1
# fi

REMOTE_URL=$(git config --get remote.origin.url)
REPO_LINK=$(echo "$REMOTE_URL" | sed -E 's#git@([^:]+):#https://\1/#; s#\.git$##')

GIT_NAME=$(git config user.name)
GIT_EMAIL=$(git config user.email)

USER_INFO=$(printf '{"userName":"%s","userEmail":"%s"}' "$GIT_NAME" "$GIT_EMAIL" | base64 -w 0)

DIFF_BASE64=$(base64 -w 0 "$TMP_DIFF_FILE")
PAYLOAD_FILE=$(mktemp)
echo "{\"diff_base64\": \"$DIFF_BASE64\", \"repoLink\": \"$REPO_LINK\", \"userInfo_base64\": \"$USER_INFO\"}" > "$PAYLOAD_FILE"
RESPONSE=$(curl -s -X POST <API_TOKEN> \
  -H "Content-Type: application/json; charset=utf-8" \
  --data-binary "@$PAYLOAD_FILE")
rm "$PAYLOAD_FILE"

echo "Service response: $RESPONSE"

exit 0

